### ISSUE TITLE
npm run dev 时报错

### ISSUE THREAD

**Issue by ddddnanana** [XavierCHN/x-template#20]
error TSTL: Could not resolve lua source files for require path 'bit' in file src\utils\sha.lua.

**Comment by XavierCHN** [comment]
目前请使用 typescript-to-lua@1.9.0，已经强制使用：3476452778dd15dc5eb32c4424aa720d72b55ebf
此外，推荐使用 yarn

**Comment by XavierCHN** [comment]
现在已经更新到 1.10.0 @ 1d4f0055e82bf9ae4e027086be04b2362c9d1e75
