### ISSUE TITLE
moddota中关于useState的用例不能显示ToggleButton Slider组件问题

### ISSUE THREAD

**Issue by ddddnanana** [XavierCHN/x-template#21]
目前我用modedota官方的例子 按钮和滑块都不显示 只能显示相关的text  
比如ToggleButton组件 
<ToggleButton
        text="Show details"
        selected={showDetails}
        onactivate={() => setShowDetails(!showDetails)}
      />

在游戏界面进入没有button可以点击 只能点击Show details文字 然后显示 showDetails

**Comment by XavierCHN** [comment]
这个是因为样式问题，需要自己写css，或者引用官方的ToggleButton样式
```
<include src="s2r://panorama/styles/dotastyles.vcss_c" />
```

**Comment by XavierCHN** [comment]
此外，你这个写法有一些问题，因为set state是异步的关系，这样`setShowDetails(!showDetails)`有时候不能得到正确的结果，具体可以参考
https://stackoverflow.com/questions/40359800/how-to-toggle-boolean-state-of-a-react-component

**Comment by ddddnanana** [comment]
已解决 谢谢！x大



---- 回复的原邮件 ----
| 发件人 | Xavier ***@***.***> |
| 日期 | 2022年09月26日 09:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [XavierCHN/x-template] moddota中关于useState的用例不能显示ToggleButton Slider组件问题 (Issue #21) |

此外，你这个写法有一些问题，因为set state是异步的关系，这样setShowDetails(!showDetails)有时候不能得到正确的结果，具体可以参考
https://stackoverflow.com/questions/40359800/how-to-toggle-boolean-state-of-a-react-component
