### ISSUE TITLE
关于用less还是scss的问题

### ISSUE THREAD

**Issue by ddddnanana** [XavierCHN/x-template#22]
你好 目前的框架是用less来生成css文件
如果我还想用scss来渲染组件的画 需要修改哪些东西 或者去哪个版本参考

**Comment by XavierCHN** [comment]
修改`webpack.dev.js`的loader即可，应该是只需要修改这部分
https://github.com/XavierCHN/x-template/blob/master/content/panorama/webpack.dev.js#L50-L76
具体的话，请参考 之前的版本： https://github.com/XavierCHN/x-template/blob/v0.0.3/content/panorama/webpack.config.js
但是建议还是直接改用 less，语法区别不大
