### ISSUE TITLE
CustomGameEventManager这个类 没有了呀 还发现了几个

### ISSUE THREAD

**Issue by ddddnanana** [XavierCHN/x-template#23]
我可能是好久没用了
今天使用发现我自己在src里写的main.ts CustomGameEventManager这个类调用不了了
还有CDOTAPlayer好像也木有了

现在使用有什么注意事项吗 我看在xnet-table.ts中还可以调用

**Comment by XavierCHN** [comment]
如果文件夹确定没有弄错，那大概率重启vscode可以解决
