### ISSUE TITLE
关于自己重写官方监听事件的问题

### ISSUE THREAD

**Issue by ddddnanana** [XavierCHN/x-template#24]
/**当物品被拾取时触发 */
    dota_item_picked_up(event:GameEventProvidedProperties & DotaItemPickedUpEvent){
        print("dota_item_picked_up")
        const item = EntIndexToHScript(event.ItemEntityIndex) as CDOTA_Item  /**转化成实例 */
        print(item.GetName())
        item.RemoveSelf()

    }
    /**注册官方事件 */
    registerofficialEvent(){
        print("registerofficialEvent")
        ListenToGameEvent("dota_item_picked_up",(event)=>this.dota_item_picked_up(event),null)

    }

我这么写 每次在控制台输入dota_create_item item_ballista 创建一个弩炮 应该走进我自己写的dota_item_picked_up函数中，但是现在确穿在了英雄身上并没有走进我的dota_item_picked_up函数，
("registerofficialEvent")这条log是可以打出来的 说明我注册成功了，请问是不是还应该设置一些什么？

**Comment by XavierCHN** [comment]
这种写法是没有问题的，如果有问题，大概是哪里的代码没写对，建议附上完整代码
不过有个小问题需要确认，如果是直接创建在单位身上的物品，是不会触发picked up的，这个只有在拾取的时候才会触发

**Comment by ddddnanana** [comment]
这个问题我试了捡东西的时候会触发我自己写的函数 但是现在遇到一个新的问题 完整代码如下
export class BackpackMain {
    Player:CDOTAPlayerController
    ItemContaineies:Record<number,ItemContainer>



    constructor(Player:CDOTAPlayerController){   
        this.Player = Player
        this.registerC2S()
        this.registerofficialEvent()       
    }
    /**初始化一个背包里的容器情况*/
    initItemContainer(){
        Array(backpackConstantTable.defaultnumber).forEach((value,index)=>{
            this.ItemContaineies[index] = new ItemContainer(index,this)
        })
    }
    s2c(key:BackpackMains2ckey,sendData:send){
        CustomGameEventManager.Send_ServerToPlayer(this.Player,key,sendData)
     
    }
    c2s_item_exchange(event:CGAMEEVENT['c2s_item_exchange']){

    }
    c2s_item_discardItems(event:CGAMEEVENT['c2s_item_discardItems']){

    }
    /**客户端要求发送所有数据*/
    c2s_item_get_totalInformation(event:CGAMEEVENT['s2c_item_send_totalInformation']){

    }
    registerC2S(){
        const registerTable:Record<registerC2S,Function>={
            "c2s_item_exchange":this.c2s_item_exchange,
            "c2s_item_discardItems":this.c2s_item_discardItems,
            "c2s_item_get_totalInformation":this.c2s_item_get_totalInformation
        }
        for(const key in registerTable){
        CustomGameEventManager.RegisterListener(key,(event)=>{
            registerTable[key](event)
        })
        }
    }

   /**查找最近的空背包容器 */
    FindEmptyContainer(){
        for(const key in this.ItemContaineies){
            if(this.ItemContaineies[key].isNull()){
                return this.ItemContaineies[key].index
            }
        }
        return -1
    }
/**当物品被拾取时触发 */
    dota_item_picked_up(event:GameEventProvidedProperties & DotaItemPickedUpEvent){
        const item = EntIndexToHScript(event.ItemEntityIndex) as CDOTA_Item  /**转化成实例 */
        print(item.GetName())
        item.RemoveSelf()
        const current_null_index = this.FindEmptyContainer()
        if(current_null_index==-1){
            return
        }
        this.ItemContaineies[current_null_index].setItem(new Item(item.GetName()))


    }
 
    
    /**注册官方事件 */
    registerofficialEvent(){
        ListenToGameEvent("dota_item_picked_up",(event)=>this.dota_item_picked_up(event),null)
    }

}


运行到   for(const key in this.ItemContaineies)这一行 就会报错
Script Runtime Error: scripts\vscripts\package/Main.ts:75: bad argument #1 to 'pairs' (table expected, got nil)

我以前都是这么用的呀 是因为什么原因呀

**Comment by ddddnanana** [comment]
你好 这个问题我解决了 我自己的容器类没有初始化 初始化之后就好了 可以关闭了
