### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by liangxiao-zs** [XavierCHN/x-template#28]
![image](https://user-images.githubusercontent.com/35052827/208584898-02e5dd07-7de5-44bd-b8d5-1f52975a0426.png)
安装成功之后 npm run dev，kv_2_js报错。求大佬解答 @XavierCHN

**Comment by XavierCHN** [comment]
因为`gulp-dotax`打包出错，请使用 `npm install gulp-dotax@^1.0.51` 处理
