### ISSUE TITLE
TS2584: Cannot find name 'console'. Do you need to change your target library?

### ISSUE THREAD

**Issue by X3CP4o2** [XavierCHN/x-template#29]
After Valve updated the javascript engine I got multiple errors regarding eval ... Function(...).

Updated my package to match yours and removed the plugin from webpack.dev.

Now i recieve:
ERROR in content/panorama/src/utils/x-nettable-dispatcher.ts:110:9
TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
    108 |         }
    109 |     } catch (error) {
  > 110 |         console.log(`x_net_table dispatch error: ${table_name} -> ${key} -> ${content}`);
        |         ^^^^^^^
    111 |     }
    112 | }
    113 |

Seems like the original panorama polyfill is missing?

**Comment by XavierCHN** [comment]
please try to restar your editor and try again if you are sure you upgrade panorama-polyfill to "@demon673/panorama-polyfill" correctly

**Comment by X3CP4o2** [comment]
> please try to restart your editor and try again if you are sure you upgrade panorama-polyfill to "@demon673/panorama-polyfill" correctly

I fixed it by importing:
import '@demon673/panorama-polyfill/lib/console';

instead of just panorama-polyfill/lib/console

thanks for answering :)
