### ISSUE TITLE
能够实现修改dota自走棋的ui界面么

### ISSUE THREAD

**Issue by ObedWang** [XavierCHN/x-template#30]
大佬，你好。

我看现在网络上的教程一般都是如何编写开发自己的地图，
想问一下，能否修改已有的rpg地图的ui，如dota自走棋这种，在棋子选择面板可以展示剩余的棋子数量等等这种功能。我在github上找到了另外一个项目:[auto-chess-ui-mode](https://github.com/auto-chess-ui-mod/source)，按照他的流程走了一下，但是没有效果，也不清楚是因为他项目过时的问题，还是我哪里没有配置对。

另外还想问一下这种行为是否被允许。

不管是否回答，都先感谢作者！！

**Comment by XavierCHN** [comment]
不建议这么做，这个模板一般也只推荐用来做全新开发

**Comment by ObedWang** [comment]
好吧 我是想要自己用 实时展示一些剩余棋子个数这种



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xavier Zheng ***@***.***&gt;
发送时间: 2023年6月2日 10:37
收件人: XavierCHN/x-template ***@***.***&gt;
抄送: Obed ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [XavierCHN/x-template] 能够实现修改dota自走棋的ui界面么 (Issue #30)





 
不建议这么做，这个模板一般也只推荐用来做全新开发
