### ISSUE TITLE
请问一下，能从游戏内存中拿到秘钥嘛？

### ISSUE THREAD

**Issue by OctoberShiyue** [XavierCHN/x-template#31]
最近才开始接触dota2，请教几个问题
dota2的lua引擎某个函数可能被hook掉嘛，作弊者能从中拿到数据吗？
一般使用GetTableValue拿到数据，有可能会被以上作弊手段拿到吗？

**Comment by XavierCHN** [comment]
只要发送到客户端，必定可以拿到

**Comment by OctoberShiyue** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
