### ISSUE TITLE
Excel to KV 报错：herolist.txt is duplicated

### ISSUE THREAD

**Issue by curry1102** [XavierCHN/x-template#36]
描述：
之前正常使用中，某个时间编辑完Excel后yarn dev 时报错
已尝试更新 gulp-dotax 到1.1.14版本，无效。

请问这是什么问题导致的？如何解决？谢谢

这是第二次在这一步出现问题报错，第一次出现问题后重装框架解决。

![YCAD4T``R_BJ8UDSQT13LTR](https://github.com/XavierCHN/x-template/assets/137892215/f493a11d-5a48-414f-b173-e7485ae8a217)

**Comment by XavierCHN** [comment]
https://github.com/XavierCHN/gulp-dotax/blob/master/src/sheetToKV.ts#L361
大概是因为你的excel文件里面有了同名同路径的sheet
