### ISSUE TITLE
yarn install 报错`C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1

### ISSUE THREAD

**Issue by xusang-zh** [XavierCHN/x-template#37]
![image](https://github.com/XavierCHN/x-template/assets/76584416/3c3ea8b7-b5cc-4c95-b587-a364979d9356)

**Comment by XavierCHN** [comment]
请尝试如下操作：
1. 移除`node_modules`文件夹
2. 使用 `yarn cache clean` 清除缓存
3. 重新 `yarn install`


如果这能解决问题，请反馈

**Comment by xusang-zh** [comment]
谢谢，这样可以解决问题
