### ISSUE TITLE
yarn dev 后出现如下报错

### ISSUE THREAD

**Issue by ooma52** [XavierCHN/x-template#40]
![image](https://github.com/XavierCHN/x-template/assets/68203535/b58098d7-56e7-496b-9e48-c7830573c803)
报错处代码：
![image](https://github.com/XavierCHN/x-template/assets/68203535/c6724db9-89b1-464e-ba2f-6a06c5bd3653)
去掉“content.table_name != null”后报错解除
我猜测content.table_name == null的情况通过了第一个if？所以会出现{ table_name: string; key: string; content: any; }这种类型的变量content，然后进行.split

纯新手，可能是我少安装了什么环境，python用的是3.10.9，nodejs按照说明中安装，lua还没有安装

**Comment by METABYTECODE** [comment]
same problem
