### ISSUE TITLE
CustomGameEventManager类函数泛型推断问题

### ISSUE THREAD

**Issue by ooma52** [XavierCHN/x-template#41]
node_modules\@moddota\dota-lua-types\types\api.generated.d.ts中，
对 CustomGameEventManager.Send_ServerToAllClients等函数进行了参数类型定义，
例：
Send_ServerToAllClients<T extends string | object>(
        eventName: (T extends string ? T : string) | keyof CustomGameEventDeclarations,
        eventData: CCustomGameEventManager.InferEventType<T, never>,
    ): void;
我发现传入参数的过程对类型泛型T产生了污染，
保持上述定义方式时：
![image](https://github.com/XavierCHN/x-template/assets/68203535/96106bc1-83fe-48c9-b189-95410bb9f43b)
 这里出现的never很诡异，输入的参数是object类型，理应在体操中不产生never类型
进行测试，将
 eventData: CCustomGameEventManager.InferEventType<T, never>,
的泛型直接改成
 eventData: T
这时的报错非常诡异：
![image](https://github.com/XavierCHN/x-template/assets/68203535/59dfb03c-1174-4ec3-8349-1c91e9582319)
由此 推测泛型T在第一个参数推断时受到了污染，尝试多定义一个泛型U对参数分别进行类型推断：
 Send_ServerToAllClients<T,U extends string | object>(
        eventName: (T extends string ? T : string) | keyof CustomGameEventDeclarations,
        eventData: CCustomGameEventManager.InferEventType<U, never>,
    ): void;
报错解除

或者有其他更好的方法？

**Comment by XavierCHN** [comment]
请到 `game/scripts/src/shared/gameevents.d.ts` 文件中声明 ``s2c_player_loading` 事件的参数类型，这样的写法是为了保证前后端数据类型的一致

当然，如果不想这么做，也可以直接：
```Typescript
CustomGameEventManager.Send_ServerToAllClients<{ param1: number }>('event_name_not_declared', { param1: 1 });
```

**Comment by ooma52** [comment]
> 请到 `game/scripts/src/shared/gameevents.d.ts` 文件中声明 ``s2c_player_loading` 事件的参数类型，这样的写法是为了保证前后端数据类型的一致
> 
> 当然，如果不想这么做，也可以直接：
> 
> ```ts
> CustomGameEventManager.Send_ServerToAllClients<{ param1: number }>('event_name_not_declared', { param1: 1 });
> ```

感谢大佬指点！
