### ISSUE TITLE
I cannot use the DOTAHeroInspect tag in tsx

### ISSUE THREAD

**Issue by LockingReal** [XavierCHN/x-template#43]
tsx not work

![image](https://github.com/XavierCHN/x-template/assets/42457717/338d310f-7cfc-4c1f-a425-4472647dea7e)

xml can work

![image](https://github.com/XavierCHN/x-template/assets/42457717/bb63f8d3-4346-48af-9337-b88b08cf1d59)

**Comment by XavierCHN** [comment]
关于此类问题，因为 Valve 经常会更改这些 xml tag，因此对于不常用的tag，请使用 `GenericPanel`，用法请参考：https://github.com/XavierCHN/react-panorama/blob/abe6170cda67a4925fecd9f5b1b0a9c1e78d110d/src/renderer/panels.ts#L126-L138
