### ISSUE TITLE
输入yarn install后出现问题

### ISSUE THREAD

**Issue by ggfd1173** [XavierCHN/x-template#44]
输入yarn install后出现
Error: getaddrinfo ENOTFOUND registry.nlark.com
at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

**Comment by XavierCHN** [comment]
属于网络问题，可以尝试强制将registry修改为npmmirror

**Comment by XavierCHN** [comment]
已在 bc883224377b3813cbaf32dbe958b3861b61e778 中将所有遗留的nlark.com替换为npmmirror.com，请尝试移除node_modules后重新install
