### ISSUE TITLE
加密发布时，abilities与modifiers的引用问题

### ISSUE THREAD

**Issue by Elricai** [XavierCHN/x-template#47]
最近在尝试使用aeslua加密发布内容，服务器端的代码都可以正常被加密解密。
我在addon.config.js文件中排除了abilities和modifiers，但有些ability与modifier会引用到一些诸如枚举、工具集、其他模块中的全局变量等加密内容。在客户端中运行时，由于在addon_game_mode_client中没有引用解密工具，这时console中会报XDecrypt为nil的错误。
我是否需要把所有被他们引用到的文件及其引用链上的文件全部取消加密？
或者有没有办法加密abilities？

**Comment by XavierCHN** [comment]
对于双端运行的内容，不建议进行加密，因为这意味着秘钥会被泄露
你可以使用类似的手段“假装”对双端运行的内容进行加密，并参考项目中的写法写一个独立的加密解密过程，并使用独立的秘钥（这本质上是一种混淆手段而不是加密手段）。
