### ISSUE TITLE
tsx中的DOTAAvatarImage似乎无效了

### ISSUE THREAD

**Issue by iamyinghe** [XavierCHN/x-template#52]
![image](https://github.com/user-attachments/assets/9dc2381f-2bef-47ba-9c84-542755ea2185)

#PlayerImage {
    width: 150px;
    height: 150px;
    background-color: red;
    horizontal-align: center;
    vertical-align: middle;
}

想尽了各种办法都无法调试出这个DOTAAvatarImage 。。。

**Comment by XavierCHN** [comment]
关于DOTAAvatarImage显示不出来的问题，请尝试使用 
`<DOTAAvatarImage style={{width: '150px', height: '150px'}} steamid='local' />`
此问题已经存在很久，原因是DOTAAvatarImage样式取不到对应css中的内容，具体原因没有深入去研究，大概率是V社的问题

**Comment by iamyinghe** [comment]
> 关于DOTAAvatarImage显示不出来的问题，请尝试使用 `<DOTAAvatarImage style={{width: '150px', height: '150px'}} steamid='local' />` 此问题已经存在很久，原因是DOTAAvatarImage样式取不到对应css中的内容，具体原因没有深入去研究，大概率是V社的问题

如您所说，这样确实可以，祝顺利~
