### ISSUE TITLE
编译的时候顺序是随机的？

### ISSUE THREAD

**Issue by takegine** [XavierCHN/x-template#6]
webpack.config.js 文件中 PanoramaManifestPlugin 函数下，的目录不写就不编译，写了也不会按顺序编译？每个xml的前后顺序是随机的？

**Comment by takegine** [comment]
webpack-panorama / lib / plugins / manifest / index.js (82)

entries.map(async (entry)=>{}  )   怀疑是这个map，不能顺序返回。是导入包的问题吗

**Comment by XavierCHN** [comment]
为何需要按顺序编译？
