### ISSUE TITLE
关于 `npm run launch`

### ISSUE THREAD

**Issue by ChouUn** [XavierCHN/x-template#9]
1. argv 里加入 `-console` 会导致 panorama 不再编译到 game 文件夹中，非本项目相关，好奇。
2. npm 更新后，将不再支持 `process.env.npm_config_argv` 的写法，详见 https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md

**Comment by XavierCHN** [comment]
fixed
